'use strict';
// Ready-made mini set for AI-related topics. Load after kit.js; draw with drawMini(key, ...).
Object.assign(MINIS, {
  claude: {
    name: 'Claude', color: '#D97757',
    pal: { O: '#D97757', S: '#B85C3E', E: '#1F1A17' }, body: 'O',
    rows: [
      '...OOOOOOOO...',
      '...OOOOOOOO...',
      '...OEOOOOEO...',
      '...OEOOOOEO...',
      'OOOOOOOOOOOOOO',
      'SOOOOOOOOOOOOS',
      '...OOOOOOOO...',
      '...S.S..S.S...',
      '...S.S..S.S...',
    ],
  },
  codex: {
    name: 'Codex', color: '#FFFFFF',
    pal: { K: '#111111', W: '#FFFFFF', E: '#111111', C: '#111111' }, body: 'W',
    rows: [
      '...KKK...KKKK...',
      '..KWWWK.KWWWWK..',
      '.KWWWWWKWWWWWWK.',
      'KWWWWWWWWWWWWWWK',
      'KWWEWWWWWWWWWWWK',
      'KWWWEWWWWWWWWWWK',
      'KWWEWWWCCCCWWWWK',
      'KWWWWWWWWWWWWWWK',
      '.KWWWWWWWWWWWWK.',
      '..KKKKKKKKKKKK..',
      '...KK......KK...',
    ],
  },
  gemini: {
    name: 'Gemini', color: '#8E75D6',
    pal: { G: (x, y) => (y < 7 ? mixHex('#4285F4', '#9B72CB', y / 7) : mixHex('#9B72CB', '#D96570', (y - 7) / 7)), E: '#FFFFFF', M: '#FFFFFF' }, body: 'G',
    rows: [
      '.......G.......',
      '.......G.......',
      '......GGG......',
      '......GGG......',
      '.....GGGGG.....',
      '....GGGGGGG....',
      '..GGGEGGGEGGG..',
      'GGGGGEGGGEGGGGG',
      '..GGGGGMGGGGG..',
      '....GGGGGGG....',
      '.....GGGGG.....',
      '......GGG......',
      '......GGG......',
      '.......G.......',
      '.......G.......',
    ],
  },
  deepseek: {
    name: 'DeepSeek', color: '#4D6BFE',
    pal: { B: '#4D6BFE', D: '#2E47C9', L: '#DDE3FF', W: '#9CC3FF', E: '#0B1440' }, body: 'B',
    rows: [
      '...W..W...........',
      '....WW............',
      '....BBBBBB........',
      '..BBBBBBBBBB....BB',
      '.BBEBBBBBBBBB..BB.',
      'BBBBBBBBBBBBBBBB..',
      'BBBBBBBBBBBBBBBD..',
      'BLLLLLLBBBBBBD.DD.',
      '.LLLLLLLLBBBD...DD',
      '..LLLLLLDDD.......',
      '....DDDD..........',
    ],
  },
  grok: {
    name: 'Grok', color: '#E8E8E8',
    pal: { D: '#141414', W: '#F2F2F2', E: '#F2F2F2' }, body: 'D',
    rows: [
      '....DDDDDD....',
      '..DDDDDDDDWW..',
      '.DDDDDDDDWWDD.',
      '.DDDDDDDWWDDD.',
      'DDDDDDDWWDDDDD',
      'DDDEDDWWDDEDDD',
      'DDDEDWWDDDEDDD',
      'DDDDWWDDDDDDDD',
      'DDDWWDDDDDDDDD',
      '.DWWDDDDDDDDD.',
      '.WWDDDDDDDDDD.',
      '..DDDDDDDDDD..',
      '....DDDDDD....',
      '...DD....DD...',
    ],
  },
  qwen: {
    name: 'Qwen', color: '#615CED',
    pal: { P: '#615CED', L: '#8F8BF7', E: '#1B1446', M: '#1B1446' }, body: 'L',
    rows: [
      '....PPPPPPP....',
      '...PPPPPPPPP...',
      '..PPLLLLLLLPP..',
      '.PPLLLLLLLLLPP.',
      'PPLLLELLLELLLPP',
      'PPLLLELLLELLLPP',
      'PPLLLLLLLLLLLPP',
      'PPLLLLMMMLLLLPP',
      '.PPLLLLLLLLLPP.',
      '..PPLLLLLLLPP..',
      '...PPPPPPPPP...',
      '....PPPPPPP....',
      '....P.....P....',
      '....P.....P....',
    ],
  },
});
